# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box_url = "https://jacderida-vagrant-boxes.s3.amazonaws.com/base_server-CentOS-6.5-x86_64.box"
  config.vm.box = "base_server-CentOS-6.5-x86_64.box"
  config.vm.network :private_network, ip: "192.168.56.105"
  config.vm.synced_folder "/home/oneilcr/dev/flask_hello_world", "/tmp/flask_hello_world"
  config.vm.provision "puppet" do |puppet|
    puppet.manifests_path = "."
    puppet.manifest_file = "apache.pp"
    puppet.module_path = "../../modules"
    puppet.options = "--verbose --debug"
  end
  config.vm.provision "shell", inline: "service iptables stop"
end
